version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ponder_postgres_case4
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=100'

volumes:
  postgres_data: 